### ISSUE TITLE
New Feature: Provide extra template slots like footer, rows per page etc

### ISSUE THREAD

**Issue by therealokoro** [HC200ok/vue3-easy-data-table#86]
It would be nice to have the table expose some extra slots especially in the footer for custom UI stylings. Take for instance, I really want to change the dropdown select menu for rows-per-page to something else. It would be nice if this can be made available via slots.

See example below

```vue
<template #rows-per-page="{ options, isActive }">
   <div v-for="(opt, i) in options" :key="i">
      <button class="button" :class="{ active: isActive }">
	{{ opt }}
      </button>
   </div>
</template>
```

**Comment by HC200ok** [comment]
<img width="871" alt="2022081101" src="https://user-images.githubusercontent.com/11552575/184052646-f37dfdda-269f-4bd9-9134-b26165dac07c.png">

Actually, if you want to customize the UI of `rows selector`, you can use:
- `theme-color` prop to customize the color of the active option
- CSS variables: `--easy-table-footer-font-color` and `--easy-table-footer-font-size` to customize the font size and font color of  `rows selector`
- CSS variables `--easy-table-rows-per-page-selector-width` and ` --easy-table-rows-per-page-selector-option-padding` to customize the width and option padding of `rows selector` (since version 1.4.13)

You can refer to the features here:
- [theme color](https://hc200ok.github.io/vue3-easy-data-table-doc/features/theme-color.html)
- [style customization](https://hc200ok.github.io/vue3-easy-data-table-doc/features/style-customization.html)

**Comment by therealokoro** [comment]
Nice walk-around, but still look into making those slots available. In my case, I do not want to use the native select menu element to render the options. Imagine having an app-wide theme or aesthetics, or a custom select menu used everywhere else but here. Not so good 😐

**Comment by HC200ok** [comment]
@therealokoro Do you mean customization like how [`Footer customization`](https://hc200ok.github.io/vue3-easy-data-table-doc/features/footer-customization.html) does?

**Comment by HC200ok** [comment]
@therealokoro I have exposed new `rows-per-page` related variables and functions:

| Name | Type |  Description |
| -------- | ----------- | ---- |
|rowsPerPageOptions | variable | Options of rows per page|
|rowsPerPageActiveOption | variable | Active option of rows per page|
|updateRowsPerPageActiveOption | function | Update active option of rows per page|

You can customize `rows-per-page` by referring to the document: 
- [Method 1: Exposed variables and functions](https://hc200ok.github.io/vue3-easy-data-table-doc/features/footer-customization.html#method-1-exposed-variables-and-functions)
- [Method 2: Composable function](https://hc200ok.github.io/vue3-easy-data-table-doc/features/footer-customization.html#method-2-composable-function)

If you want to add a custom select menu used everywhere, `slots` is not a good choice, because you can't change the position of `rows-per-page` (always inside of the native footer of `vue3-easy-data-table` ).

**Comment by therealokoro** [comment]
This works out fine. I'll be sure to make adjustments to my code.

Thank you for your efforts. I'll be sure to make suggestions to make this library even better. Thumbs up👍
